import Link from 'next/link'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js'
}

const navLinks = [
  {
    label: 'Home',
    route: '/'
  },
  {
    label: 'About',
    route: '/about'
  }
]

export default function RootLayout ({ children }) {
  return (
    <html lang='en'>
      <head>
        <title>My first app with next 13</title>
      </head>
      <body>
        <header>
          <nav>
            <ul>
              {navLinks.map(link => <li key={link.route}><Link href={link.route}>{link.label}</Link></li>)}
            </ul>
          </nav>
        </header>
        {children}
      </body>
    </html>
  )
}
